- name: Install software
  yum: pkg={{ item }} state=present
  with_items:
    - vim
    - tmux
    - htop
    - ncdu
    - ranger
    - parallel
    - git
    - the_silver_searcher
    - zsh
    - kpcli
    - shred

- name: change shell to zsh
  user: name={{ user }} shell=/bin/zsh

- include: dotfiles.yml

