- name: Install software
  openbsd_pkg: name={{ item }} state=present
  with_items:
    - zsh
    - ncdu
    - parallel
    - the_silver_searcher
    - kpcli

- package: name=htop
  when: ansible_os_family != "OpenBSD"

- shell: 'which zsh'
  register: zsh_path

- name: change shell to zsh
  user: name={{ user }} shell={{ zsh_path.stdout }}

- name: Link dotfiles
  file: >-
    src={{ item }}
    dest=/home/{{ user }}/.{{ item | basename }}
    mode=0600
    state=link
  with_fileglob:
    - ./*

- name: Link dot-directories
  file: src={{ role_path }}/files/{{ item }} dest=/home/{{ user }}/.{{ item }} state=link
  with_items:
    - zsh
    - bin
