- name: Install software
  dnf: pkg={{ item }} state=installed
  with_items:
    - cmus
    - clementine
    - gimp
    - inkscape
    - ImageMagick
    - audacity
    - vlc
    - smplayer
    - sox
    - flac
    - shntool
    - cuetools

- name: Install codecs
  dnf: pkg={{ item }} state=present
  with_items:
    - gstreamer-plugins-ugly
    - gstreamer-plugins-bad
    - gstreamer-ffmpeg

