- name: Install software
  dnf: name={{ item }} state=installed
  with_items:
    - clementine
    - gimp
    - inkscape
    - ImageMagick
    - audacity
    - vlc
    - smplayer

- name: Install codecs
  dnf: name={{ item }} state=present
  with_items:
    - gstreamer-plugins-ugly
    - gstreamer-plugins-bad
    - gstreamer-ffmpeg

