export LC_ALL=en_AU.UTF-8

$HOME/.bin/input-cfg.sh

export DESKTOP_SESSION=gnome &&
xrdb -merge $HOME/.Xresources &
xsetroot -solid '#657b83' &

xscreensaver &
conky &
exec dbus-launch --exit-with-session --sh-syntax cwm
