- name: Install the nibbler/iojs COPR
  copy: src=nibbler-iojs-fedora-21.repo dest=/etc/yum.repos.d

- name: Install io.js
  yum: name={{ item }} state=present
  with_items:
    - iojs
    - iojs-npm

