- name: Install Development Tools
  dnf: name="@Development Tools" state=present

- name: Install Development Libraries
  dnf: name="@Development Libraries" state=present

- name: Install Development-related tools
  dnf: name={{ item }} state=present
  with_items:
    - tig
    - meld
    - golang

- file: path=/home/{{ user }}/Code state=directory
  sudo: false

- include: google-chrome.yml
- include: postgresql.yml
- include: mongodb.yml
- include: redis.yml

