- name: Install Development-related tools
  package: name={{ item }} state=present
  with_items:
    - base-devel
    - meld
    - go

- file: path=/home/{{ user }}/Code state=directory
  sudo: false

- include: postgresql.yml
- include: mongodb.yml
- include: redis.yml

