- name: Install Development Tools
  yum: name="@Development Tools" state=present

- name: Install Development Libraries
  yum: name="@Development Libraries" state=present

- name: Install Development-related tools
  yum: name={{ item }} state=present
  with_items:
    - git
    - tig
    - meld
    - golang

- name: Create the Projects directory
  file: path=/home/{{ user }}/{{ item }} state=directory
  with_items:
    - Projects
    - Source
  sudo: false

- include: google-chrome.yml
- include: postgresql.yml
- include: iojs.yml
- include: mongodb.yml
- include: redis.yml

