- name: Install PostgreSQL server
  package: name=postgresql state=installed

  # arch:
  # sudo su - postgres -c "initdb --locale en_AU.UTF-8 -D '/var/lib/pgsql/data'"

- name: be sure postgresql is running and enabled
  service: name=postgresql state=running enabled=yes

